# Spring application properties
spring:
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
    database: mysql
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: true

  # Data base properties
  datasource:
    url: "jdbc:mysql://localhost:3306/bisket?useSSL=false&zeroDateTimeBehavior=convertToNull&noAccessToProcedureBodies=true&sessionVariables=wait_timeout=600&serverTimezone=Asia/Seoul"
    username: ""
    password: ""
    hikari:
      maximum-pool-size: 30
      minimum-idle: 2
      idle-timeout: 60000
      max-lifetime: 300000
      pool-name: hikari-cp

# API server properties
server:
  port: 8080
  servlet:
    context-path: /v1